// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static get currentPlatform {
    if (kIsWeb) {
      throw UnimplementedError(
          'DefaultFirebaseOptions have not been configured for web - '
          'you can reconfigure this by running the FlutterFire CLI again.');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-FmQsrpukeJWzTK-gQu_Mvk1y-QK5c-M',
    appId: '1:314671411264:android:6a009efa1d1094e3cfafa5',
    messagingSenderId: '314671411264',
    projectId: 'uas-21312030',
    storageBucket: 'uas-21312030.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDpTixq7KS4YAyZ5Xq1NmO5A5Xt3dcaQU',
    appId: '1:314671411264:ios:043bdf2ca97a20a1cfafa5',
    messagingSenderId: '314671411264',
    projectId: 'uas-21312030',
    storageBucket: 'uas-21312030.appspot.com',
    iosBundleId: 'com.tekno.uas21312030',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDpTixq7KS4YAyZ5Xq1NmO5A5Xt3dcaQU',
    appId: '1:314671411264:ios:45079b91ba7d491fcfafa5',
    messagingSenderId: '314671411264',
    projectId: 'uas-21312030',
    storageBucket: 'uas-21312030.appspot.com',
    iosBundleId: 'com.tekno.uas21312030.RunnerTests',
  );
}
